version: "3"
services:
  web:
    restart: always
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    restart: always
    image: mdillon/postgis
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
